version: '3'

volumes:
  postgres_volume:

services:
  playlist:
    environment:
      - CONFIG_PATH=config.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    depends_on:
      - pg

  pg:
    image: postgres:14-alpine3.17
    env_file:
      - config.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  migrator:
    build:
      context: .
      dockerfile: migration.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg
    depends_on:
      - pg